from typing import Union
from .html import ColorHtml

class StaticColorHtml:

    @staticmethod
    def thin(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bold(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def italic(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def through(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def underline(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def hidden(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def black(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def red(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def green(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def yellow(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def blue(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def magenta(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def cyan(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def white(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bright_black(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bright_red(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bright_green(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bright_yellow(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bright_blue(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bright_magenta(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bright_cyan(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bright_white(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_black(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_red(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_green(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_yellow(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_blue(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_magenta(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_cyan(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_white(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_bright_black(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_bright_red(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_bright_green(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_bright_yellow(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_bright_blue(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_bright_magenta(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_bright_cyan(text: Union[str | ColorHtml]) -> ColorHtml: ...
    @staticmethod
    def bg_bright_white(text: Union[str | ColorHtml]) -> ColorHtml: ...