from typing import TypeVar, Union
from .color import Color

_T = TypeVar("_T", bound="StaticColor")

class StaticColor:
    @staticmethod
    def bold(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def dim(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def italic(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def underline(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def through(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def reverse(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def blink(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def blink_fast(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def hidden(text: Union[str | Color]) -> Color: ...

    # region fg

    @staticmethod
    def black(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def red(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def green(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def yellow(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def blue(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def magenta(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def cyan(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def white(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bright_black(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bright_red(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bright_green(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bright_yellow(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bright_blue(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bright_magenta(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bright_cyan(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bright_white(text: Union[str | Color]) -> Color: ...

    # region bg

    @staticmethod
    def bg_black(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_red(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_green(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_yellow(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_blue(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_magenta(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_cyan(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_white(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_bright_black(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_bright_red(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_bright_green(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_bright_yellow(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_bright_blue(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_bright_magenta(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_bright_cyan(text: Union[str | Color]) -> Color: ...
    @staticmethod
    def bg_bright_white(text: Union[str | Color]) -> Color: ...
